import Control.Applicative
import Data.List
import Data.List.Unique

input :: String
input = "ubkfmdjxyzlbgkrotcepvswaqx uikfmdkuyzlbgerotcepvswaqh uikfmdpxyzlbgnrotcepvswoeh nikfmdjxyzlbgnrotqepvswyqh qgkfmdjxyzlbgnmotcepvswaqh uikfmdjxyzqbgnrytcepvsbaqh uikfmdjxyzibgprotcecvswaqh uikfmajxyzlcgnrojcepvswaqh uvkfsdjxyzlbgnrotcepvjwaqh uikfmdjxfzlbggrotcepvswawh uikfmhjxyzlbgnuotcepvjwaqh uikfmdjxyzlbuzcotcepvswaqh uikfmdwxyzlbgnrotcepvfwamh uikfmdexyzlbgnroecepvswhqh uikfmdjuyzlbgnrotcqpvswafh uikfddjxyzvbgnrotceppswaqh yikfwdjxyzlbgnrotcepvswagh uiktmdjxyzlbgnrotceposwajh uikfmdsxyzlbgnroteetvswaqh uikfpdjxyzlbgnroncepvswuqh uikfmtjxyzlbgurotcepvswaoh eikfmdjxyjlbgnrotcepyswaqh uikfkdjxyzlbgnrotcepvszaqv uikfrdjxtwlbgnrotcepvswaqh uikfmdjxyzlbgnrotpepwswahh kikfmdjxyzlbgnkotcepvswqqh uikfkduxyzlbgnrotcepvswafh uikfxhjxyzlbgnrotcegvswaqh uikfmdjxyzlmgnrotcenvawaqh uzkfmddxyzlbgnrltcepvswaqh uikfmdjxyzlbgnrobcepisqaqh uijfmdjxyzlbgnrotcexvrwaqh uiwjmdjxyzlbgnrotceprswaqh uhkqmdjxwzlbgnrotcepvswaqh uiktmsjxyzwbgnrotcepvswaqh uikfmdjxyztbgnqotcepvswcqh uibfmdjxyzlbgnroqcepvswaqx uwkfmdjxyxlbgnrotcfpvswaqh uikumdjxyzlbgnrstceposwaqh uikfzdjxyznhgnrotcepvswaqh uikuydjxyzlbgnrotqepvswaqh uikfmdqxyzlbgnrotfefvswaqh yikfmdjxyzlbrnrqtcepvswaqh uiifmdjxyzlbenrotcfpvswaqh uxkjmdjxyzlbgnrotcmpvswaqh uikgmdjxyzlbgnrotceovlwaqh uikfmdjxyzvbgzrotcenvswaqh uiufmdjxyzlbgnrotceposwazh uiafmdjxyzlignmotcepvswaqh uikfmdjxyzwbgnsotlepvswaqh uikjmdjvyzlbgnrotcenvswaqh uikfmdjxyzlbonroteepvswaqi uikfmdjxyzldgnroxcepviwaqh uikvmdjxyzlbgdrotrepvswaqh uikfmdjyyzwbgnrotcepvzwaqh uikfmdjxyzzbnnvotcepvswaqh uikomdjxyzlbgnrotcepvuwhqh uikfmmjxyzbbgnrotcepvswayh uikfmdjfezlbgprotcepvswaqh uzkfmojxmzlbgnrotcepvswaqh uipfmdjxyzlbgnrotceyuswaqh uikfmdjxyzlkgnmotcepvswadh uikfmdjxyzlbgnuctcbpvswaqh uikfqdjxyzlbogrotcepvswaqh uikfmdjxyzlfynrotcepvswash uikfmdjxizzmgnrotcepvswaqh uhkfmdjxyzlbhnrotcenvswaqh uipfmdjxyzlbgorotcepfswaqh uikfmdjxyznbgnrotcepvswfah uikfmujxyzlbgnrotnepvssaqh uikfmdjxyzlxgnrotcepvsrwqh uikfmdjxszlbgnrottvpvswaqh umkfmdskyzlbgnrotcepvswaqh uikfmdjxyzlbgorotcwpzswaqh uikfmdhxyzzbgnzotcepvswaqh jikfmdjxyzlbgnrotcepveyaqh uirfmdlxyzlbgnjotcepvswaqh uikfmdjxyzlbgnrorxepvswazh uikfmdjxyzltgnrotcepvsxaqi uikfmdjxyzlbxlrotcepkswaqh uvkfmdjxyzlbgnrotcopvswxqh uxkfmdjxkzlbgnrotcepvswqqh uikfmdjxyzlbqnrotcepvhwrqh uikfmdjxyzlvgnrolcepvswrqh urkfmdixyzlbgnrotcepvsjaqh uikfmdjxymlbsnrotcepvswcqh uikfmdjxyilbgnrotcepvcwzqh uikfadjxlzlbgnrotcepvswaql uikfmdjxuzlbgdrotcgpvswaqh yikfmdgxyzlbgnrotcepvswarh uikfmdjxyzlbgorotcepcswaqv uikkmdjxyzlbvnrotcepvvwaqh uwzfmdjxyxlbgnrotcfpvswaqh uikfmdjxyztbgnrotcrtvswaqh uiufmdjxyzhbgnrotcupvswaqh uikfzdjcyzlbgnrotcfpvswaqh uipfmdjxyzlbgnrotavpvswaqh uikfmajxyzlbgnrotcepbsxaqh uikfmdjfyzlbgnrotbepvswmqh gikkmdjxyzlbgnrptcepvswaqh uikfmdjxqvlbgnrotsepvswaqh fikfmdjxyzlbgnrotcegvswoqh idkfmdjxyzlbgnrotcepwswaqh uikfmdqxyzlbmnrobcepvswaqh uikfmdjxyzpbgnroicepvsyaqh uikfmkoxyzlbgnrotcgpvswaqh unkfmdjxyzlbpnrolcepvswaqh uikfmdjmyzlbgfrotcupvswaqh ujkfmdjxynlbgnroteepvswaqh uikfmljxyzlbgnaotcepvsiaqh uikfmdjdyzlbgnrotcepvtwaqd uikfmdjxyzlbgnyotcepimwaqh uikfmdjxyzfbjnrotcepvxwaqh eiwfmdjxyzlbgnrdtcepvswaqh umkhmdjxyzlbgnrotceivswaqh uikfmdjxyzlbgnrotcwpvswneh uckfmdjxyzlbknrotcepvswauh uiofmdjoyzlbgnrbtcepvswaqh uikfmdbxyzlbgnrotcepaslaqh uimfmdjxyalbgnrotcepvswaxh uqkfmdjxyzlbwnrotcepmswaqh uiyfmdjxyzlbgnrotcepvswxuh uikfmdjxyzlbgmrotgepvswamh uikfmdjxyqlbgarozcepvswaqh uikfmdjxyzabanpotcepvswaqh uikfmdjgyzlbsnrotcepvswaqj uikfmdjxyzlbwnrottepvsvaqh uikfmdjxyzlbbnrotcepvofaqh uikfudjxyzlbgnustcepvswaqh cskfmqjxyzlbgnrotcepvswaqh uiwfmddxyzlbgnrotccpvswaqh eikpmdjxyzlbgnrotcesvswaqh uikfmdzxyzlngnrrtcepvswaqh uikfmdjxyzlbgnrotcepaswtph uirfmdjxyzlbgnrotcepvswsqe uikjmdjxqzlbgirotcepvswaqh uikfmdjxsllbknrotcepvswaqh uikfmdjxyqlbgcrotcepvswaqu uikfmdjsymlbgnrotcebvswaqh uikfmdjxezlbgnroccepviwaqh uikfmdjiyzjbgnrotcepvswarh uqkfmdjxyzmbgnrotcepvslaqh unkfmdjxyzlbinrotceplswaqh uikfmdjxyzpbgnrjtcedvswaqh uicfmdjxyzlbgrrotcepvswamh ukknmdjxyzlbgnqotcepvswaqh uikfudjxyzlbdnrztcepvswaqh uikfmdjxyzlbgnrozcepvswawk uikfmduxyzsbgnrotcepvswauh uikfmdjxyzljbnrotcenvswaqh uukfmdjxyzlbgnrotcckvswaqh uilfldjxyzlbgnrotcdpvswaqh uckfmdjxyvybgnrotcepvswaqh qikfmdjxyglbgnrotcepvrwaqh uikfmhjxyzltgnrotcepvswbqh uikfmdjxipabgnrotcepvswaqh uikfmdjxyzlbgnrotceovswanl uikfmdjxyzlbgirotcapvswahh uikfucjxyflbgnrotcepvswaqh pikfmdjxyzpbgnrotcepvswaeh uikfmdjiyylbgnrotcervswaqh uikfmdjgyzlbgnrotcaevswaqh uikvmdjxyzlbunrotcepvswarh uikfadjuyzpbgnrotcepvswaqh uikfmdjxyzlbgnrotcepsawaqj eikfmdjxyflbgnrotcepvswaeh uisfmdaxyzlbgnrotcepvswlqh vikfmdjxyzlzgnrotcepvswanh ukkfmdoxyzlbgnrotcewvswaqh uikfmdhxyzlbgnrotcrpvbwaqh uhkfmdjwezlbgnrotcepvswaqh uikfddjxyzlbgnroteepvpwaqh uikfmdjxczlbgncotiepvswaqh uikfvdjxyzlbgnrotcnpvsaaqh uikfmdjxyzlbgnritcepvlwmqh uikfmdjxczlcgnrotcecvswaqh mikfmdjxyzlbgnrotcepvswasi uifvmdjxyzlbgnrotpepvswaqh uikzmdjxyzlbgnrotrepvswaqs uikfmqjqyzlbunrotcepvswaqh uikfpdyxyzlbgnrotcepvswagh uikfmdjxyzobgnrotrlpvswaqh zisdmdjxyzlbgnrotcepvswaqh uikfmdjxyzlbgnlotiesvswaqh uikfddixyzlbgnroucepvswaqh uijfmdrxyzlbgnrotoepvswaqh uikfmdcxbzlbgnrotcepvpwaqh uikfmdjxxzlbfnrotcecvswaqh upkfmdjxyzmtgnrotcepvswaqh uikfmdrxyzlbgnrjtcepvswaqp uizfmdjxyzlbsnrotcepviwaqh uidfmdjxyslbgnrotcxpvswaqh uikfmdjxyzlbgnrovyepvsdaqh uiafmdjxyzlbgnrxtcepvsdaqh ugkfmdjxyzlbgnrodcepvswawh pikfmtjxyzhbgnrotcepvswaqh uikfmdjxyzlfgnvotcepvswtqh uikbmdjxyzlbgerotcepvswaqm uikfmdjxyhlbdnrotcepvswaqy uikfgdjxyzlbgnhotcepvswdqh uikfmdpxyzlbgnrotcepvscanh uikfmdjxyzsbgnretcepvswaqn uikfddjxyzlrgnrotcepvsbaqh uikfmdjxyzlbgnrotcqnrswaqh uhkfmejxyzlbgnrotvepvswaqh uikimdjxyzlngnrotceprswaqh uikfmdjxyzwbunrotiepvswaqh rikfmdjxyzlbgnrotcypvssaqh uikfmdjxyzlbdnrotcrpvswsqh uekfmdjxkzlbznrotcepvswaqh uikfmdjxyglbgvrotcepvswaqv uikfmcjxyzlbgnrotmeovswaqh uikfmdjxyznbgnrozcepvswaqm uikfmdjxyzlbdnrotcepdsyaqh umkfmdjxfzlbgnrotiepvswaqh uitfmdjxyzvbcnrotcepvswaqh uikfmdjqyzlbgnrvtcepvlwaqh uikfmdjxyzkbworotcepvswaqh uikfmdzxyzlbwnrotcypvswaqh uikfmdjxyklbgnrftyepvswaqh uinfmsjxyzlbgnrotcepsswaqh xisfmdjxymlbgnrotcepvswaqh uikfmdjxjzlbgnropcepvswaqv uikfmdjxyalegyrotcepvswaqh uikfydjxyzlbgnrotcekvswtqh uikwmojxyzlbgnromcepvswaqh uikdmdjayzlbgnrotcepvswzqh uikfmdjxyzlmvnrotctpvswaqh uikfmbjxyzlbgnrotceptsweqh yvkfmdjxyzlbgqrotcepvswaqh uikomdjxfxlbgnrotcepvswaqh uikfmdjxczlbgnroocepgswaqh uikemdjxizlbgnrotcegvswaqh uikdmdjxyzlbgwrotceprswaqh tiyfmdjfyzlbgnrotcepvswaqh tmkfmdjxyzlbgirotcepvswaqh uikfmdjxyzebgnzotcepqswaqh uikfmljxyzlbgnrwtcepvswaeh uikfmojxyzlbgnrotcepbswwqh uikfmdjxyzlbgsrotcewvswwqh uikfmdjhyzlbgdrogcepvswaqh uikfmvjxyzlbrnrltcepvswaqh jikfmdjxyzlbgnrotcepvgcaqh uikhtdjxyzlbgnrotcepvswarh uikfmdjxyezbgnritcepvswaqh uikfwdjxyzlbgnrotzepvsnaqh uikfmdjxqylbgnrobcepvswaqh zikzmdjxyzlbgnrhtcepvswaqh uiksmzjxyzlbgnrftcepvswaqh uikfmdjxuzlbgnrotcepvsvaqc"

inputCodes :: [String]
inputCodes = words input

containsDuplicate :: String -> Bool
containsDuplicate = containsNplicate 2

containsTriplicate :: String -> Bool
containsTriplicate = containsNplicate 3

containsNplicate :: Int -> String -> Bool
containsNplicate n str = any (== n) $ map snd (count str)

inputCodesWithDuplicates :: [String]
inputCodesWithDuplicates = filter containsDuplicate inputCodes

inputCodesWithTriplicates :: [String]
inputCodesWithTriplicates = filter containsTriplicate inputCodes

result1 :: Int
result1 = length inputCodesWithDuplicates * length inputCodesWithTriplicates

numberOfDifferences :: Eq a => [a] -> [a] -> Int
numberOfDifferences [] [] = 0
numberOfDifferences [] ys = length ys
numberOfDifferences xs [] = length xs
numberOfDifferences (x:xs) (y:ys) = (if x == y then 0 else 1) + numberOfDifferences xs ys

differInJustOne :: [(String, String)]
differInJustOne = [(x,y) | x <- inputCodes, y <- inputCodes, numberOfDifferences x y == 1]

commonElements :: String -> String -> String
commonElements [] [] = []
commonElements _ [] = []
commonElements [] _ = []
commonElements (x:xs) (y:ys) = if x == y then x : commonElements xs ys else commonElements xs ys

result2 :: String
result2 = (uncurry commonElements . head) differInJustOne
